name: Build Clang

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux
    name: archlinux

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
            pacman --noconfirm -Syu base-devel \
          bc \
          bison \
          ccache \
          clang \
          cpio \
          cmake \
          flex \
          git \
          libelf \
          lld \
          llvm \
          ninja \
          openssl \
          python3 \
          uboot-tools

    - name: Build Clang
      run: |
        mkdir build
        cd build
        git clone https://github.com/onettboots/boolx-clang-build -b nbase
        cd boolx-clang-build
        git config --global user.name "atusyarif"
        git config --global user.email "atusyaripudin@gmail.com"
        git clone https://github.com/llvm/llvm-project -b llvmorg-20-init
        source utils.sh
        bash build_llvm.sh --shallow-clone --polly-opt --llvm-opt --bolt-opt
        bash build_binutils.sh --targets=ARM,ARM64,X86
        tar -czf clang20.tar.gz install
        curl bashupload.com -T clang20.tar.gz
